version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: nestjs-api-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - .docker/database/postgres/initdb/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=example,example_test
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    tmpfs:
      - /var/lib/postgresql
    networks:
      - default

volumes:
   postgres:
    driver: local

networks:
  default:
    driver: bridge
